name: Close inactive

on:
  workflow_call:

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v10
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          operations-per-run: 1000

          days-before-issue-stale: 21
          days-before-issue-close: 7
          stale-issue-label: "Stale"
          exempt-issue-labels: "needs work,needs more work"
          stale-issue-message: >
            This issue has been inactive for 3 weeks. It will be closed in 1 week
            if there is no follow-up.
          close-issue-message: >
            Closing this issue because there has been no follow-up for 4 weeks.

          days-before-pr-stale: 21
          days-before-pr-close: 7
          stale-pr-label: "Stale"
          exempt-pr-labels: "needs work,needs more work"
          stale-pr-message: >
            This pull request has been inactive for 3 weeks. It will be closed in
            1 week if there is no follow-up.
          close-pr-message: >
            Closing this pull request because there has been no follow-up for 4 weeks.
